### ISSUE TITLE
Support for encrypted ZFS root w. LUKS (Ubuntu/Mint)

### ISSUE THREAD

**Issue by antevens** [zabbly/zfs#1]
This is 1/2 bug report 1/2 just a note for others wanting to update their kernel on Ubuntu or Mint systems.

The following is needed to boot systems with encrypted root filesystems.

1. Install the new kernel and ZFS modules as listed in this repository the and the zabbly kernel repo.
2. Edit the the ZFS initramfs scripts, add the following section and then rebuilt your initramfs
3. Reboot

Edit  /usr/share/initramfs-tools/scripts/zfs and add the following section at line 914 (currently), after finding and importing the correct pool and before preparing the root filesystem

	# ------------
	# Open and mount luks keystore for any pools using one
	CRYPTROOT=/scripts/local-top/cryptroot
	# We already processed original crypttab by calling local-top. Only add zvol related ones now.
	if [ -x "${CRYPTROOT}" ]; then
	        TABFILE=/cryptroot/crypttab
	        :>"${TABFILE}"
		# Wait for all keystore devices in /dev/zvol to appear with a 5s timeout
		timeout=50
		NUMKS=$(zfs list -H -o name | grep '/keystore$' | wc -l)
		while [ ${NUMKS} -ne $(find /dev/zvol/ -name 'keystore' | wc -l) ]; do
			if [ $timeout -le 0 ]; then
				break
			fi
			sleep .1
			timeout=$((timeout - 1))
		done
		# Locate, then mount the keystore volumes
		for ks in $(find /dev/zvol/ -name 'keystore'); do
			[ ! -e "${ks}" ] && continue
			pool="$(basename $(dirname ${ks}))"
			echo "keystore-${pool} ${ks} none luks,discard" >> "${TABFILE}"
		done
		${CRYPTROOT}
		for dev in $(find /dev/mapper -name 'keystore-*'); do
			# Translate filename to path
			storepath="/run/$(echo $(basename ${dev})|sed -e 's,-,/,')"
			mkdir -p "${storepath}"
			mount "${dev}" "${storepath}"
		done
	fi

Update the initramfs (currently)
update-initramfs -c -k 6.6.11-zabbly+

**Comment by stgraber** [comment]
Hey there,

This repository uses the upstream zfs packaging scripts and logic, so best would be to get this resolved by ZFS upstream.

Can you file a bug at https://github.com/openzfs/zfs or even a pull request to update the script?

The script is located at contrib/initramfs/scripts/zfs inside of the repository.

**Comment by antevens** [comment]
Sure, I'll file a bug upstream but the code snippet isn't mine (copied from the Cannonical version of the package) so I don't feel comfortable making an MR for them.

**Comment by bmilde** [comment]
Can confirm that I have the same problem when installing zabbly kernels into a fresh ubuntu 24.04 zfs installation with enc. Adding the CRYPTROOT code snippet into  /usr/share/initramfs-tools/scripts/zfs  as suggested by @antevens solves the issue and the zabbly kernel boots correctly with zfs+enc. Thanks for the tip! Can we get a modified version of this into zabbly/zfs ?

**Comment by stgraber** [comment]
Might be worth someone affected sending the change you're doing as a pull request on the ZFS upstream project. In my experience, issues don't get picked up particularly quickly over there, but pull requests do tend to get reviewed and included.
